baseURL = "https://ffvitu.netlify.app/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Felix Fernando"
googleAnalytics = ""

theme = "hermit"
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 5  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/

[author]
  name = "Felix Fernando"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"

  homeSubtitle = "My Personal Blog."

  justifyContent = true  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  
  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/ffvitu"

  [[params.social]]
    name = "github"
    url = "https://github.com/ffVitu"

[menu]

  [[menu.main]]
    name = "Post"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
